backend:
  name: git-gateway
  repo: alex-elizabeth/alex-elizabeth.github.io
  branch: main

# Agrega esta línea con tu enlace de Netlify:
site_domain: teal-maamoul-54f6ea.netlify.app
media_folder: "imagenes"
public_folder: "imagenes"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: ""
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - { label: "Imagen de portada", name: "image", widget: "image", required: false }
      - { label: "Contenido del Artículo", name: "body", widget: "markdown" }
